//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HosInfoManager.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_HosInfoManagerTYPE          130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDB_BACKGROUND                  311
#define IDD_DIALOG_KE_Cha               312
#define IDD_DIALOG_KE_Guan              313
#define IDD_DIALOG_Peo_Cha              314
#define IDD_DIALOG_Peo_Guan             315
#define IDD_DIALOG_BR_Cha               316
#define IDD_DIALOG_BR_Guan              317
#define IDD_DIALOG_BF_Guan              318
#define IDD_DIALOG_Log                  319
#define IDB_Log                         321
#define IDC_STATIC_Teacher              1000
#define IDC_STATIC_Author               1001
#define IDC_STATIC_KE_Cha               1002
#define IDC_EDIT_KE_Cha                 1003
#define IDC_BUTTON1                     1004
#define IDC_BUTTON_Cha                  1004
#define IDC_BUTTON_KE_Guan_Insert       1004
#define IDC_BUTTON_Peo_Cha              1004
#define IDC_BUTTON_Peo_Guan_Insert      1004
#define IDC_BUTTON_BR_Cha               1004
#define IDC_BUTTON_BR_Guan_Insert       1004
#define IDC_BUTTON_BF_Guan_Insert       1004
#define IDC_LIST_KE_Cha                 1005
#define IDC_STATIC_KE_Guan_Insert       1006
#define IDC_EDIT_KE_Guan_KNo            1007
#define IDC_EDIT_KE_Guan_KName          1008
#define IDC_EDIT_KE_Guan_KTel           1009
#define IDC_EDIT_KE_Guan_Zhuren         1010
#define IDC_EDIT_KE_Guan_Hushizhang     1011
#define IDC_STATIC_KE_Guan_KNo          1012
#define IDC_STATIC_KE_Guan_KName        1013
#define IDC_STATIC_KE_Guan_KTel         1014
#define IDC_STATIC_KE_Guan_Zhuren       1015
#define IDC_STATIC_KE_Guan_Hushizhang   1016
#define IDC_LIST_KE_Guan                1017
#define IDC_STATIC_KE_Guan_Del          1018
#define IDC_STATIC_KE_Guan_Del1         1019
#define IDC_EDIT_KE_Guan_Del            1020
#define IDC_BUTTON_KE_Guan_Del          1021
#define IDC_STATIC_Peo_Cha_kuang        1022
#define IDC_EDIT_Peo_Cha                1023
#define IDC_LIST_Peo_Cha                1024
#define IDC_STATIC_Peo_Cha              1025
#define IDC_EDIT_Peo_Guan_PNo           1026
#define IDC_EDIT_Peo_Guan_KNo           1027
#define IDC_EDIT_Peo_Guan_PName         1028
#define IDC_EDIT_Peo_Guan_PLel          1029
#define IDC_LIST_Peo_Guan               1030
#define IDC_EDIT_Peo_Guan_Del           1031
#define IDC_BUTTON_Peo_Guan_Del         1032
#define IDC_STATIC_Peo_Guan_Insert      1033
#define IDC_STATIC_Peo_Guan_PNo         1034
#define IDC_STATIC_Peo_Guan_KNo         1035
#define IDC_STATIC_Peo_Guan_PName       1036
#define IDC_STATIC_Peo_Guan_PLel        1037
#define IDC_STATIC_Peo_Guan_Del_kuang   1038
#define IDC_STATIC_Peo_Guan_Del         1039
#define IDC_STATIC_BR_Cha               1040
#define IDC_STATIC_BR_Cha_1             1041
#define IDC_EDIT_BR_Cha                 1042
#define IDC_LIST_BR_Cha                 1043
#define IDC_EDIT_BR_Guan_BFNo           1044
#define IDC_EDIT_BR_Guan_BCNo           1045
#define IDC_EDIT_BR_Guan_BRName         1046
#define IDC_EDIT_BR_Guan_KNo            1047
#define IDC_EDIT_BR_Guan_PNo            1048
#define IDC_EDIT_BR_Guan_BRInfo         1049
#define IDC_LIST_BR_Guan                1050
#define IDC_EDIT_BR_Guan_BFNo_Del       1051
#define IDC_EDIT_BR_Guan_BCNo_Del       1052
#define IDC_BUTTON_BR_Guan_Del          1053
#define IDC_STATIC_BR_Guan_IN_K         1054
#define IDC_STATIC_BR_Guan_BFNo         1055
#define IDC_STATIC_BR_Guan_BCNo         1056
#define IDC_STATIC_BR_Guan_BRName       1057
#define IDC_STATIC_BR_Guan_KNo          1058
#define IDC_STATIC_BR_Guan_PNo          1059
#define IDC_STATIC_BR_Guan_BRInfo       1060
#define IDC_STATIC_BR_Guan_Del_K        1061
#define IDC_STATIC_BR_Guan_BFNo_        1062
#define IDC_STATIC_BR_Guan_BCNo_        1063
#define IDC_STATIC_BF_Guan_Insert_K     1064
#define IDC_EDIT_BF_Guan_BFNo           1065
#define IDC_EDIT_BF_Guan_KNo            1066
#define IDC_EDIT_BF_Guan_Acc            1067
#define IDC_LIST_BF_Guan                1068
#define IDC_EDIT_BF_Guan_Del            1069
#define IDC_BUTTON_BF_Guan_Del          1070
#define IDC_STATIC_BF_Guan_BFNo         1071
#define IDC_STATIC_BF_Guan_KNo          1072
#define IDC_STATIC_BF_Guan_BFAcc        1073
#define IDC_STATIC_BF_Guan_Del          1074
#define IDC_STATIC_BF_Guan_BFNo_Del     1075
#define IDC_EDIT_NAME                   1076
#define IDC_EDIT_PSW                    1077
#define IDC_STATIC_Name                 1078
#define IDC_STATIC_PSW                  1079
#define IDC_STATIC_LOG                  1080
#define ID_SAILOR_SAILOR                32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_Menu_KE_Cha                  32777
#define ID_Menu_KE_Guan                 32778
#define ID_Menu_Peo_Cha                 32779
#define ID_Menu_Peo_Guan                32780
#define ID_Menu_BL_Cha                  32781
#define ID_Menu_BL_Guan                 32782
#define ID_32783                        32783
#define ID_                             32784
#define ID_Menu_BingFang_Guan           32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        322
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
